# Generated by Django 2.2.16 on 2020-11-12 00:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0002_auto_20201111_1457'),
        ('schedule', '0002_auto_20201111_1505'),
    ]

    operations = [
    ]
