# Generated by Django 2.2.16 on 2020-11-12 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='latitude',
            field=models.CharField(default='', max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='place',
            name='logitude',
            field=models.CharField(default='', max_length=15),
            preserve_default=False,
        ),
    ]
