# Generated by Django 2.2.16 on 2020-11-05 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0002_auto_20201028_1022'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='course_name',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='place',
            name='time',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='place',
            name='dong',
            field=models.CharField(max_length=50),
        ),
    ]
