# Generated by Django 2.2.16 on 2020-11-12 01:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0002_auto_20201112_0933'),
    ]

    operations = [
        migrations.RenameField(
            model_name='place',
            old_name='logitude',
            new_name='longitude',
        ),
    ]
