# Generated by Django 2.2.16 on 2020-11-05 04:31

from django.db import migrations, models
import tour.models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0003_auto_20201105_1316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='image',
            field=models.ImageField(upload_to=tour.models.course_directory_path),
        ),
    ]
