# Generated by Django 2.2.16 on 2020-11-10 08:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0001_initial'),
        ('review', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='place',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='tour.Place'),
            preserve_default=False,
        ),
    ]
